apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sheetflow.fullname" . }}-config
  labels:
    {{- include "sheetflow.labels" . | nindent 4 }}
data:
  SERVER_PORT: "{{ .Values.api.port }}"
  MAX_UPLOAD_SIZE: "{{ .Values.api.env.maxUploadSize }}"
  {{- if .Values.minio.enabled }}
  S3_ENDPOINT: "http://{{ include "sheetflow.fullname" . }}-minio:9000"
  S3_BUCKET: "{{ .Values.minio.bucket }}"
  S3_USE_PATH_STYLE: "true"
  {{- else }}
  S3_BUCKET: "{{ .Values.api.env.s3Bucket }}"
  S3_REGION: "{{ .Values.api.env.s3Region }}"
  S3_USE_PATH_STYLE: "{{ .Values.api.env.s3UsePathStyle }}"
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ include "sheetflow.fullname" . }}-redis:6379"
  {{- end }}
  METRICS_PORT: "{{ .Values.worker.metricsPort }}"
