apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheetflow.fullname" . }}-secret
  labels:
    {{- include "sheetflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  DATABASE_URL: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "sheetflow.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"
  {{- else if .Values.api.env.databaseUrl }}
  DATABASE_URL: "{{ .Values.api.env.databaseUrl }}"
  {{- end }}
  {{- if not .Values.redis.enabled }}
  {{- if .Values.api.env.redisUrl }}
  REDIS_URL: "{{ .Values.api.env.redisUrl }}"
  {{- end }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  S3_ACCESS_KEY: "{{ .Values.minio.rootUser }}"
  S3_SECRET_KEY: "{{ .Values.minio.rootPassword }}"
  {{- end }}
